### ISSUE TITLE
Rakarrack-lv2 recipe is not compiling

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/meta-pedalpi#42] opened 2021-01-10 15:59 UTC
Rakarrack-lv2 recipe is not compiling due to unrecognized compile flags:
| aarch64-poky-linux-g++: error: unrecognized command line option '-msse'
| aarch64-poky-linux-g++: error: unrecognized command line option '-msse2'
| aarch64-poky-linux-g++: error: unrecognized command line option '-mfpmath=sse'

Patch has been removed from recipe.
I wonder if there is a way to tune or remove those compiler flags from the recipe without a path.
I tried the following but didn't work:
TARGET_CXXFLAGS_remove = "-msse -msse2 -mfpmath=sse"

The following didn't work either:
TUNE_CCARGS := "${@oe.utils.str_filter_out('-msse', '${TUNE_CCARGS}', d)}"
TUNE_CCARGS := "${@oe.utils.str_filter_out('-msse2', '${TUNE_CCARGS}', d)}"
TUNE_CCARGS := "${@oe.utils.str_filter_out('-mfpmath=sse', '${TUNE_CCARGS}', d)}"

**Comment by auto3000** [comment] 2021-01-10 16:51
The flags -msse -msse2 are only added on non-arm machines:
https://github.com/ssj71/rkrlv2/blob/master/lv2/CMakeLists.txt#L9
You may suspect you have a previous version of rakarrack source code.


Le dim. 10 janv. 2021 à 16:59, Rezzonics <notifications@github.com> a
écrit :

**Comment by Rezzonics** [comment] 2021-01-10 18:17
Recipe is not pointing to master but here:
https://github.com/ssj71/rkrlv2/blob/7edcb4e29a358623bfd57fa2c27e5da60adfcec3/CMakeLists.txt

**Comment by Rezzonics** [comment] 2021-01-10 18:34
Sorry, it's also here:
https://github.com/ssj71/rkrlv2/blob/7edcb4e29a358623bfd57fa2c27e5da60adfcec3/lv2/CMakeLists.txt
Maybe for some reason I don't have set CMAKE_SYSTEM_PROCESSOR

**Comment by auto3000** [comment] 2021-01-10 18:58
You are correct with the issue, I'm able to reproduce locally with odroid-c2 build. But I don't know why my CI job building odroid-c2 does not catch the issue !

**Comment by auto3000** [comment] 2021-01-10 19:03
Indeed the CI jobs detects the odroid-c2 vs msse option issue : https://app.circleci.com/pipelines/github/auto3000/pedalpi-dev-platform/135/workflows/ec747d48-28ca-4a1a-a728-97d8855a35c7/jobs/2638/parallel-runs/0/steps/0-104

But since I have not merged the updated submodule, and another issue (related to bundler recipe) was breaking the CI first, i missed it.

**Comment by auto3000** [comment] 2021-01-10 19:13
On odroid-c2, the CMAKE_SYSTEM_PROCESSOR aarch64, I'm preparing a patch...

**Closed as completed** 2021-01-10 20:02 UTC

**Comment by auto3000** [comment] 2021-01-10 20:07
Let me know if you are catching again this problem... :(

**Comment by Rezzonics** [comment] 2021-01-10 20:17
It works now, thanks
